[workspace]
resolver = "2"
members = [
    "crates/trd-core",
    "crates/trd-cli",
    "crates/trd-wasm",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/Hong-Xiang/trd"

[workspace.dependencies]
trd-core = { path = "crates/trd-core" }

[workspace.metadata.crane]
name = "trd"
