[package]
name = "trd-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "trd"
path = "src/main.rs"

[dependencies]
trd-core.workspace = true
clap = { version = "4", features = ["derive"] }
env_logger = "0.11"
log = "0.4"
image = { version = "0.25", default-features = false, features = ["png", "jpeg"] }
