#!/usr/bin/env python3
"""Generate current params/GLB goldens and external stills without changing cameras.

uv run --with pyarrow --with numpy --with pillow python scripts/golden_fixtures.py
Expected PNGs are never regenerated by this tool.
"""

import json
import subprocess
import sys
import tempfile
import uuid
from pathlib import Path

import pyarrow as pa
from PIL import Image

from glb_assets import glb_bytes, image_to_rgba, png_bytes
from obj_geometry import parse_obj
from protocol_version import PROTOCOL_VERSION

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "crates/trd-core/tests/golden"
FRAMES = [0, 62, 124]
WIDTH, HEIGHT = 320, 180
QUAD = """v -1 -1 0 0 1 1
v 1 -1 0 0 1 1
v 1 1 0 0 1 1
v -1 1 0 0 1 1
f 1 2 3
f 1 3 4
"""


def mesh(text, texture=None):
    position, color, uv, index = parse_obj(text)
    values = {"position": position, "index": index}
    if color:
        values["color"] = color
    if uv:
        values["uv"] = uv
    return glb_bytes(values, texture)


def build_stage(stage, temporary):
    lines = (ROOT / f"examples/frames.cornellbox.stage{stage}.jsonl").read_text().splitlines()
    rows = []
    for resource, index in enumerate(FRAMES):
        row = json.loads(lines[index])
        if "k" in row:
            for element in [0, 4, 6, 7]:
                row["k"][element] *= 1 / 3
        old_path = row.get("frame_path", "")
        name = Path(old_path).stem
        digits = "".join(character for character in name if character.isdigit())
        video_index = int(digits) if digits else index
        jpg = temporary / f"{stage}-{resource}.jpg"
        subprocess.run([
            "ffmpeg", "-nostdin", "-loglevel", "error", "-y",
            "-i", str(ROOT / "assets/videos/cornellbox/CameraMovement.mp4"),
            "-vf", f"select=eq(n\\,{video_index}),scale={WIDTH}:{HEIGHT}:flags=area",
            "-frames:v", "1", "-fps_mode", "passthrough", "-q:v", "2", str(jpg),
        ], check=True)
        suffix = "jpg" if stage == 1 else "png"
        row["frame_path"] = f"frames/stage{stage}-resource-{resource}.{suffix}"
        row.pop("frame_url", None)
        row.pop("frame_id", None)
        target = OUT / row["frame_path"]
        target.parent.mkdir(parents=True, exist_ok=True)
        if stage == 1:
            target.write_bytes(jpg.read_bytes())
        else:
            with Image.open(jpg) as image:
                target.write_bytes(png_bytes(image.convert("RGBA")))
        rows.append(row)
    jsonl = temporary / f"stage{stage}.jsonl"
    jsonl.write_text("".join(json.dumps(row) + "\n" for row in rows), encoding="utf-8")
    params = subprocess.run([sys.executable, str(ROOT / "scripts/jsonl_to_arrow.py"), str(jsonl), "--no-shadows"],
                            capture_output=True, check=True).stdout
    resources = []
    if stage == 2:
        h, w, rgba = image_to_rgba(ROOT / "assets/meshes/bunny_with_texture/bunny_uv_map1.jpg", 128)
        texture = png_bytes(Image.fromarray(rgba.reshape(h, w, 4)))
        resources.append(mesh((ROOT / "assets/meshes/bunny_with_texture/bunny.obj").read_text(), texture))
    resources.append(mesh(QUAD))
    schema = pa.schema(
        [pa.field("mesh_id", pa.uuid(), nullable=False), pa.field("glb", pa.large_binary(), nullable=False)],
        metadata={b"trd.protocol.version": PROTOCOL_VERSION.encode(), b"trd.table.kind": b"mesh"},
    )
    ids = [uuid.uuid5(uuid.NAMESPACE_URL, f"trd:golden:stage{stage}:{index}").bytes for index in range(len(resources))]
    batch = pa.RecordBatch.from_arrays(
        [pa.array(ids, type=pa.uuid()), pa.array(resources, type=pa.large_binary())], schema=schema,
    )
    path = OUT / f"stage{stage}.arrow"
    with path.open("wb") as output:
        output.write(params)
        with pa.ipc.new_stream(output, schema) as writer:
            writer.write_batch(batch)
    print(f"wrote {path}: params first, {len(resources)} GLBs, {len(rows)} external backgrounds")


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as directory:
        for stage in (1, 2):
            build_stage(stage, Path(directory))


if __name__ == "__main__":
    main()
